steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "-m", "-q", "cp", "-r", "gs://cache.alunduil.com/blog.alunduil.com", "/cabal" ]
    volumes:
      - name: 'cabal-config'
        path: '/cabal'

  - name: 'haskell:8.0'
    args: [ 'cabal', 'update' ]
    volumes:
      - name: 'cabal-config'
        path: '/builder/home/.cabal'
  - name: 'haskell:8.0'
    args: [ 'cabal', 'install', '-j', '--only-dependencies', '--avoid-reinstalls' ]
    volumes:
      - name: 'cabal-config'
        path: '/builder/home/.cabal'
  - name: 'haskell:8.0'
    args: [ 'cabal', 'run', 'site', 'build' ]
    volumes:
      - name: 'cabal-config'
        path: '/builder/home/.cabal'

  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "-m", "-q", "rsync", "-r", "-d", "/cabal", "gs://cache.alunduil.com/blog.alunduil.com" ]
    volumes:
      - name: 'cabal-config'
        path: '/cabal'

  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "-m", "rsync", "-r", "-d", "_site/", "gs://$_DOMAIN/" ]

timeout: "60m"
