steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull', 'gcr.io/$PROJECT_ID/builder-blog.alunduil.com' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '--cache-from', 'gcr.io/$PROJECT_ID/builder-builder-blog.alunduil.com',
            '-t', 'gcr.io/$PROJECT_ID/builder-blog.alunduil.com',
            '-f', 'Dockerfile', '.' ]

  - name: 'gcr.io/$PROJECT_ID/builder-blog.alunduil.com'
    args: [ 'build' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ '-m', 'rsync', '-r', '-d', '_site/', 'gs://$_DOMAIN/' ]

images:
  - 'gcr.io/$PROJECT_ID/builder-blog.alunduil.com'

timeout: 60m
