steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/site:$BRANCH_NAME", "." ]
  - name: "gcr.io/$PROJECT_ID/site:$BRANCH_NAME"
    args: [ "build" ]
  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "-m", "rsync", "-r", "-d", "_site/", "gs://d.blog.alunduil.com/" ]
timeout: "3600s"
images:
  - "gcr.io/$PROJECT_ID/site:$BRANCH_NAME"
