steps:
  - name: "haskell"
    args: [ "cabal", "sandbox", "init" ]
  - name: "haskell"
    args: [ "cabal", "configure" ]
  - name: "haskell"
    args: [ "cabal", "build" ]
  - name: "haskell"
    args: [ "./dist/build/site/site", "build" ]
  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "-m", "rsync", "-r", "-d", "_site/", "gs://blog.alunduil.com/" ]
