steps:
  - name: 'haskell:8.0'
    args: [ 'cabal', 'update' ]
    volumes:
      - name: 'cabal-config'
        path: '/builder/home/.cabal'
  - name: 'haskell:8.0'
    args: [ 'cabal', 'install', '-j', '--only-dependencies' ]
    volumes:
      - name: 'cabal-config'
        path: '/builder/home/.cabal'
  - name: 'haskell:8.0'
    args: [ 'cabal', 'run', 'site', 'build' ]
    volumes:
      - name: 'cabal-config'
        path: '/builder/home/.cabal'

  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "-m", "rsync", "-r", "-d", "_site/", "gs://r.blog.alunduil.com/" ]

timeout: "60m"
