steps:
  - name: "mgarrido/nikola"
    args: [ "nikola", "build" ]
  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "-m", "rsync", "-rd", "output/", "gs://blog.alunduil.com/" ]
  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "-m", "acl", "ch", "-r", "-u", "AllUsers:R", "gs://blog.alunduil.com/" ]
